import { invoicesRepo } from '../repositories/invoices.repo.js';
import { HttpError } from '../utils/http-error.js';

const MANAGER_ROLES = ['SUPERADMIN', 'REDITEL', 'ADMINISTRACE', 'VEDOUCI'];

function roundCurrency(value) {
  return Number((Number(value) || 0).toFixed(2));
}

function formatDatePart(date) {
  const pad = (value) => String(value).padStart(2, '0');
  return `${date.getFullYear()}${pad(date.getMonth() + 1)}${pad(date.getDate())}`;
}

function buildInvoiceNumber(prefix = 'FA', stampDate = new Date()) {
  const random = String(Math.floor(Math.random() * 900) + 100);
  return `${prefix}-${formatDatePart(stampDate)}-${random}`;
}

function resolveEmployeeName(employee) {
  const fullName = [employee.firstName, employee.lastName].filter(Boolean).join(' ').trim();
  return fullName || employee.email;
}

function calculateAttendanceSummary(attendanceRows = []) {
  const rows = [...attendanceRows].sort((a, b) => new Date(a.createdAt) - new Date(b.createdAt));
  let openShift = null;
  let workHours = 0;
  const attendanceDays = new Set();
  const absenceDays = new Set();
  const projectNames = new Set();

  for (const row of rows) {
    const rowDate = new Date(row.createdAt);
    const dayKey = rowDate.toISOString().slice(0, 10);
    if (row.projectName) projectNames.add(row.projectName);

    if (row.status && row.status !== 'PRACE') {
      absenceDays.add(dayKey);
      continue;
    }

    if (row.type === 'PRICHOD') {
      openShift = { date: rowDate, dayKey };
      attendanceDays.add(dayKey);
      continue;
    }

    if (row.type === 'ODCHOD' && openShift) {
      const diffHours = (rowDate.getTime() - openShift.date.getTime()) / 3600000;
      if (diffHours > 0) {
        workHours += Math.min(diffHours, 16);
        attendanceDays.add(openShift.dayKey);
      }
      openShift = null;
    }
  }

  return {
    workHours: roundCurrency(workHours),
    attendanceDays: attendanceDays.size,
    absenceDays: absenceDays.size,
    projectNames: [...projectNames]
  };
}

export const invoicesService = {
  async create(user, payload) {
    const invoiceNumber = payload.invoiceNumber?.trim() || buildInvoiceNumber('FA');
    const amount = roundCurrency(payload.amount);
    const vatRate = Number(payload.vatRate ?? 0);
    const amountVat = roundCurrency(amount * (vatRate / 100));
    const employeeId = user.role === 'MONTER' ? user.id : (payload.employeeId || null);
    const clientName = payload.clientName?.trim() || (user.role === 'MONTER' ? user.email : null);

    const result = await invoicesRepo.create({
      companyId: user.companyId,
      employeeId,
      invoiceNumber,
      clientName,
      amount,
      amountVat,
      amountTotal: roundCurrency(amount + amountVat),
      currency: payload.currency || 'CZK',
      vatRate,
      dueDate: payload.dueDate || null,
      projectId: payload.projectId || null,
      variableSymbol: payload.variableSymbol || null,
      constantSymbol: payload.constantSymbol || null,
      note: payload.note || null,
      autoGenerated: false,
      sourceType: 'MANUAL',
      summaryJson: payload.summaryJson || {}
    });
    return result.rows[0];
  },

  async createAutoFromAttendance(user, payload) {
    const employeeId = payload.employeeId || user.id;
    if (user.role === 'MONTER' && employeeId !== user.id) {
      throw new HttpError(403, 'Montér může vystavit automatickou fakturu jen za sebe');
    }

    const employeeResult = await invoicesRepo.getEmployee(user.companyId, employeeId);
    const employee = employeeResult.rows[0];
    if (!employee) throw new HttpError(404, 'Zaměstnanec nebyl nalezen');

    const periodFrom = new Date(payload.periodFrom);
    const periodTo = new Date(payload.periodTo);
    if (Number.isNaN(periodFrom.getTime()) || Number.isNaN(periodTo.getTime()) || periodFrom > periodTo) {
      throw new HttpError(400, 'Neplatné období fakturace');
    }

    const attendanceRows = (await invoicesRepo.getAttendanceForEmployee({
      companyId: user.companyId,
      employeeId,
      periodFrom: periodFrom.toISOString(),
      periodTo: periodTo.toISOString(),
      projectId: payload.projectId || null
    })).rows;

    const logRows = (await invoicesRepo.getLogsForEmployee({
      companyId: user.companyId,
      employeeId,
      periodFrom: periodFrom.toISOString(),
      periodTo: periodTo.toISOString(),
      projectId: payload.projectId || null
    })).rows;

    const attendanceSummary = calculateAttendanceSummary(attendanceRows);
    const logEntries = logRows.length;
    const unitRate = roundCurrency(payload.hourlyRate);
    const logRate = roundCurrency(payload.logRate || 0);
    const bonusAmount = roundCurrency(payload.bonusAmount || 0);
    const workAmount = roundCurrency(attendanceSummary.workHours * unitRate);
    const logAmount = roundCurrency(logEntries * logRate);
    const totalAmount = roundCurrency(workAmount + logAmount + bonusAmount);

    if (totalAmount <= 0) {
      throw new HttpError(400, 'Za zvolené období není co fakturovat');
    }

    const employeeName = resolveEmployeeName(employee);
    const invoiceNumber = payload.invoiceNumber?.trim() || buildInvoiceNumber('AUTO');
    const projectLabel = attendanceSummary.projectNames.length ? `Projekt: ${attendanceSummary.projectNames.join(', ')}` : 'Projekt: všechny';
    const note = [
      `Automatické interní vyúčtování pro ${employeeName}`,
      `Období: ${periodFrom.toLocaleDateString('cs-CZ')} – ${periodTo.toLocaleDateString('cs-CZ')}`,
      `Odpracováno: ${attendanceSummary.workHours} h × ${unitRate} Kč`,
      `Denní záznamy: ${logEntries} × ${logRate} Kč`,
      `Bonus / korekce: ${bonusAmount} Kč`,
      projectLabel,
      payload.note?.trim() || ''
    ].filter(Boolean).join(' | ');

    const result = await invoicesRepo.create({
      companyId: user.companyId,
      employeeId,
      invoiceNumber,
      clientName: employee.email,
      amount: totalAmount,
      amountVat: 0,
      amountTotal: totalAmount,
      currency: payload.currency || 'CZK',
      vatRate: 0,
      dueDate: payload.dueDate || null,
      projectId: payload.projectId || null,
      note,
      autoGenerated: true,
      sourceType: 'AUTO_ATTENDANCE',
      periodFrom: periodFrom.toISOString(),
      periodTo: periodTo.toISOString(),
      workHours: attendanceSummary.workHours,
      attendanceDays: attendanceSummary.attendanceDays,
      logEntries,
      unitRate,
      logRate,
      bonusAmount,
      summaryJson: {
        employeeName,
        employeeEmail: employee.email,
        attendanceDays: attendanceSummary.attendanceDays,
        absenceDays: attendanceSummary.absenceDays,
        workHours: attendanceSummary.workHours,
        workAmount,
        logEntries,
        logAmount,
        bonusAmount,
        projectNames: attendanceSummary.projectNames,
        source: 'AUTO_ATTENDANCE'
      }
    });
    return result.rows[0];
  },

  async markPaid(user, payload) {
    if (user.role === 'MONTER') {
      throw new HttpError(403, 'Montér nemůže označovat faktury jako zaplacené');
    }
    const result = await invoicesRepo.markPaid({ companyId: user.companyId, id: payload.id });
    return result.rows[0];
  }
};
