import { query } from '../config/db.js';

export const invoicesRepo = {
  create({
    companyId,
    employeeId = null,
    invoiceNumber,
    clientName = null,
    amount,
    amountVat = 0,
    amountTotal,
    currency = 'CZK',
    vatRate = 0,
    dueDate = null,
    projectId = null,
    variableSymbol = null,
    constantSymbol = null,
    note = null,
    autoGenerated = false,
    sourceType = 'MANUAL',
    periodFrom = null,
    periodTo = null,
    workHours = null,
    attendanceDays = 0,
    logEntries = 0,
    unitRate = null,
    logRate = null,
    bonusAmount = 0,
    summaryJson = {}
  }) {
    return query(
      `INSERT INTO "Invoice" (
        id, "companyId", "employeeId", "invoiceNumber", "clientName", amount, "amountVat", "amountTotal", currency, "vatRate",
        status, "dueDate", "issuedAt", "projectId", "variableSymbol", "constantSymbol", note,
        "autoGenerated", "sourceType", "periodFrom", "periodTo", "workHours", "attendanceDays", "logEntries",
        "unitRate", "logRate", "bonusAmount", "summaryJson", "createdAt", "updatedAt"
      )
      VALUES (
        gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7, $8, $9,
        'ISSUED', $10, NOW(), $11, $12, $13, $14,
        $15, $16, $17, $18, $19, $20, $21,
        $22, $23, $24, $25::jsonb, NOW(), NOW()
      ) RETURNING *`,
      [
        companyId,
        employeeId,
        invoiceNumber,
        clientName,
        amount,
        amountVat,
        amountTotal ?? amount + amountVat,
        currency,
        vatRate,
        dueDate,
        projectId,
        variableSymbol,
        constantSymbol,
        note,
        autoGenerated,
        sourceType,
        periodFrom,
        periodTo,
        workHours,
        attendanceDays,
        logEntries,
        unitRate,
        logRate,
        bonusAmount,
        JSON.stringify(summaryJson || {})
      ]
    );
  },

  markPaid({ companyId, id }) {
    return query(
      `UPDATE "Invoice"
       SET status = 'ZAPLACENO', "paidAt" = NOW(), "updatedAt" = NOW()
       WHERE id = $1 AND "companyId" = $2
       RETURNING *`,
      [id, companyId]
    );
  },

  getEmployee(companyId, employeeId) {
    return query(
      `SELECT id, email, role, "firstName", "lastName", phone
       FROM "User"
       WHERE id = $1 AND "companyId" = $2`,
      [employeeId, companyId]
    );
  },

  getAttendanceForEmployee({ companyId, employeeId, periodFrom, periodTo, projectId = null }) {
    return query(
      `SELECT a.*, p.name as "projectName"
       FROM "Attendance" a
       LEFT JOIN "Project" p ON a."projectId" = p.id
       WHERE a."companyId" = $1
         AND a."userId" = $2
         AND a."createdAt" >= $3
         AND a."createdAt" <= $4
         AND ($5::uuid IS NULL OR a."projectId" = $5)
       ORDER BY a."createdAt" ASC`,
      [companyId, employeeId, periodFrom, periodTo, projectId]
    );
  },

  getLogsForEmployee({ companyId, employeeId, periodFrom, periodTo, projectId = null }) {
    return query(
      `SELECT d.*, p.name as "projectName"
       FROM "DailyLog" d
       LEFT JOIN "Project" p ON d."projectId" = p.id
       WHERE d."companyId" = $1
         AND d."authorId" = $2
         AND d."logDate" >= $3
         AND d."logDate" <= $4
         AND ($5::uuid IS NULL OR d."projectId" = $5)
       ORDER BY d."logDate" ASC`,
      [companyId, employeeId, periodFrom, periodTo, projectId]
    );
  }
};
