ALTER TABLE "Invoice"
  ADD COLUMN IF NOT EXISTS "employeeId" UUID REFERENCES "User"(id) ON DELETE SET NULL;

ALTER TABLE "Invoice"
  ADD COLUMN IF NOT EXISTS "autoGenerated" BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE "Invoice"
  ADD COLUMN IF NOT EXISTS "sourceType" TEXT NOT NULL DEFAULT 'MANUAL';

ALTER TABLE "Invoice"
  ADD COLUMN IF NOT EXISTS "periodFrom" TIMESTAMPTZ;

ALTER TABLE "Invoice"
  ADD COLUMN IF NOT EXISTS "periodTo" TIMESTAMPTZ;

ALTER TABLE "Invoice"
  ADD COLUMN IF NOT EXISTS "workHours" DOUBLE PRECISION;

ALTER TABLE "Invoice"
  ADD COLUMN IF NOT EXISTS "attendanceDays" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "Invoice"
  ADD COLUMN IF NOT EXISTS "logEntries" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "Invoice"
  ADD COLUMN IF NOT EXISTS "unitRate" DOUBLE PRECISION;

ALTER TABLE "Invoice"
  ADD COLUMN IF NOT EXISTS "logRate" DOUBLE PRECISION;

ALTER TABLE "Invoice"
  ADD COLUMN IF NOT EXISTS "bonusAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE "Invoice"
  ADD COLUMN IF NOT EXISTS "summaryJson" JSONB NOT NULL DEFAULT '{}'::jsonb;

CREATE INDEX IF NOT EXISTS "idx_Invoice_employeeId_createdAt"
  ON "Invoice" ("employeeId", "createdAt" DESC);

INSERT INTO "RolePermission" (id, role, "permissionId", granted)
SELECT gen_random_uuid(), 'MONTER', p.id, TRUE
FROM "Permission" p
WHERE p.key = ANY (ARRAY['invoices.read', 'invoices.create'])
ON CONFLICT (role, "permissionId") DO NOTHING;

INSERT INTO "RolePermission" (id, role, "permissionId", granted)
SELECT gen_random_uuid(), 'VEDOUCI', p.id, TRUE
FROM "Permission" p
WHERE p.key = ANY (ARRAY['invoices.read', 'invoices.create'])
ON CONFLICT (role, "permissionId") DO NOTHING;
