import {
  LayoutDashboard,
  Clock,
  HardHat,
  BookOpen,
  Calculator,
  Receipt,
  Package,
  Users,
  Settings,
  FileText,
  Upload,
  Download,
  PenSquare,
  Bot,
  ShieldAlert,
  Stethoscope,
  Printer,
  KeyRound,
  Sliders,
  Ruler,
  Truck
} from 'lucide-react';

export const NAV_ITEMS = [
  { id: 'reporty', icon: LayoutDashboard, label: 'Reporty', roles: ['SUPERADMIN', 'REDITEL', 'ADMINISTRACE', 'VEDOUCI'] },
  { id: 'dochazka', icon: Clock, label: 'Docházka', roles: ['SUPERADMIN', 'REDITEL', 'ADMINISTRACE', 'VEDOUCI', 'MONTER'] },
  { id: 'projekty', icon: HardHat, label: 'Projekty', roles: ['SUPERADMIN', 'REDITEL', 'ADMINISTRACE', 'VEDOUCI', 'MONTER'] },
  { id: 'denik', icon: BookOpen, label: 'Deník', roles: ['SUPERADMIN', 'REDITEL', 'VEDOUCI', 'MONTER'] },
  { id: 'kalkulacka', icon: Calculator, label: 'Kalkulačka', roles: ['SUPERADMIN', 'REDITEL', 'ADMINISTRACE', 'VEDOUCI', 'MONTER'] },
  { id: 'faktury', icon: Receipt, label: 'Faktury', roles: ['SUPERADMIN', 'REDITEL', 'ADMINISTRACE', 'VEDOUCI', 'MONTER'] },
  { id: 'sklad', icon: Package, label: 'Sklad', roles: ['SUPERADMIN', 'REDITEL', 'ADMINISTRACE', 'VEDOUCI', 'MONTER'] },
  { id: 'asistent', icon: Bot, label: 'AI Asistent', roles: ['SUPERADMIN', 'REDITEL', 'ADMINISTRACE', 'VEDOUCI', 'MONTER'] },
  { id: 'autodetect', icon: Ruler, label: 'AI AutoDetect (foto)', roles: ['SUPERADMIN', 'REDITEL', 'ADMINISTRACE', 'VEDOUCI', 'MONTER'] },
  { id: 'distribuce', icon: Truck, label: 'Distribuce & nákup', roles: ['SUPERADMIN', 'REDITEL', 'ADMINISTRACE', 'VEDOUCI'] },
  { id: 'kolize', icon: ShieldAlert, label: 'Kolize', roles: ['SUPERADMIN', 'REDITEL', 'ADMINISTRACE', 'VEDOUCI', 'MONTER'] },
  { id: 'projekt-asistent', icon: Stethoscope, label: 'AI troubleshooting', roles: ['SUPERADMIN', 'REDITEL', 'VEDOUCI', 'MONTER'] },
  { id: 'tlak', icon: Printer, label: 'Tisk dokumentů', roles: ['SUPERADMIN', 'REDITEL', 'ADMINISTRACE', 'VEDOUCI'] },
  { id: 'team', icon: Users, label: 'Team', roles: ['SUPERADMIN', 'REDITEL', 'ADMINISTRACE', 'VEDOUCI'] },
  { id: 'nastaveni', icon: Settings, label: 'Nastavení', roles: ['SUPERADMIN', 'REDITEL'] },
  { id: 'documents', icon: FileText, label: 'Dokumenty', roles: ['SUPERADMIN', 'REDITEL', 'ADMINISTRACE', 'VEDOUCI'] },
  { id: 'imports', icon: Upload, label: 'Importy', roles: ['SUPERADMIN', 'REDITEL', 'ADMINISTRACE'] },
  { id: 'exports', icon: Download, label: 'Exporty', roles: ['SUPERADMIN', 'REDITEL', 'ADMINISTRACE'] },
  { id: 'signatures', icon: PenSquare, label: 'Podpisy', roles: ['SUPERADMIN', 'REDITEL', 'ADMINISTRACE'] },
  { id: 'licence', icon: KeyRound, label: 'Licence', roles: ['SUPERADMIN', 'REDITEL'] },
  { id: 'platforma', icon: Sliders, label: 'Platforma (SUPERADMIN)', roles: ['SUPERADMIN'] }
];
