function metersLabel(value) {
  if (value === null || value === undefined || Number.isNaN(Number(value))) return '—';
  const number = Number(value);
  if (number >= 1000) return `${(number / 1000).toFixed(2)} km`;
  return `${Math.round(number)} m`;
}

export function DashboardPage({ db }) {
  const totalRevenue = (db.invoices || []).reduce((sum, item) => sum + Number(item.amount || 0), 0);
  const totalArea = (db.components || []).reduce((sum, item) => sum + Number(item.surfaceArea || 0), 0);
  const assignedUsers = new Set((db.assignments || []).map((x) => x.userId)).size;
  const autoInvoices = (db.invoices || []).filter((item) => item.autoGenerated).length;
  const outsideAttendance = (db.attendance || []).filter((item) => item.geoStatus === 'OUT_OF_RADIUS').length;
  const logPhotos = (db.logs || []).reduce((sum, log) => sum + (Array.isArray(log.attachments) ? log.attachments.length : 0), 0);

  const cards = [
    { label: 'Aktivní projekty', value: db.projects?.length || 0 },
    { label: 'Uživatelé', value: db.users?.length || 0 },
    { label: 'Obsazené osoby', value: assignedUsers },
    { label: 'Fakturace', value: `€ ${totalRevenue.toFixed(2)}` },
    { label: 'Plocha výroby', value: `${totalArea.toFixed(2)} m²` }
  ];

  const alerts = (db.attendance || [])
    .filter((item) => item.geoStatus === 'OUT_OF_RADIUS' || item.geoStatus === 'NO_GPS')
    .slice(0, 5);

  return (
    <div className="space-y-6">
      <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-5">
        {cards.map((card) => (
          <div key={card.label} className="rounded-3xl border border-slate-800 bg-slate-900 p-5">
            <p className="text-xs font-bold uppercase tracking-widest text-slate-500">{card.label}</p>
            <p className="mt-3 text-2xl font-black text-white">{card.value}</p>
          </div>
        ))}
      </section>

      <section className="grid gap-4 md:grid-cols-3">
        <div className="rounded-3xl border border-slate-800 bg-slate-900 p-5">
          <p className="text-xs font-bold uppercase tracking-widest text-slate-500">Auto faktury</p>
          <p className="mt-3 text-2xl font-black text-emerald-400">{autoInvoices}</p>
        </div>
        <div className="rounded-3xl border border-slate-800 bg-slate-900 p-5">
          <p className="text-xs font-bold uppercase tracking-widest text-slate-500">Docházka mimo stavbu</p>
          <p className="mt-3 text-2xl font-black text-amber-400">{outsideAttendance}</p>
        </div>
        <div className="rounded-3xl border border-slate-800 bg-slate-900 p-5">
          <p className="text-xs font-bold uppercase tracking-widest text-slate-500">Fotky v deníku</p>
          <p className="mt-3 text-2xl font-black text-blue-400">{logPhotos}</p>
        </div>
      </section>

      <section className="grid gap-6 lg:grid-cols-2">
        <div className="rounded-3xl border border-slate-800 bg-slate-900 p-5">
          <h2 className="mb-4 text-sm font-black uppercase tracking-widest text-emerald-400">Klientské firmy v síti</h2>
          <div className="space-y-3">
            {(db.allCompanies || []).map((company) => (
              <div key={company.id} className="rounded-2xl border border-slate-800 bg-slate-950 p-4">
                <div className="flex items-center justify-between gap-3">
                  <div>
                    <p className="font-bold text-white">{company.name}</p>
                    <p className="text-xs text-slate-500">Majitel: {company.owner || 'neuvedeno'}</p>
                  </div>
                  <span className={`rounded-full px-3 py-1 text-xs font-black ${company.isActive ? 'bg-emerald-950 text-emerald-400' : 'bg-rose-950 text-rose-400'}`}>
                    {company.isActive ? 'Licence aktivní' : 'Licence blokována'}
                  </span>
                </div>
              </div>
            ))}
            {!db.allCompanies?.length && <p className="text-sm text-slate-500">Seznam firem je dostupný pouze pro roli SUPERADMIN.</p>}
          </div>
        </div>

        <div className="rounded-3xl border border-slate-800 bg-slate-900 p-5">
          <h2 className="mb-4 text-sm font-black uppercase tracking-widest text-blue-400">GPS a provozní upozornění</h2>
          <div className="space-y-3">
            {alerts.map((item) => (
              <div key={item.id} className="rounded-2xl border border-slate-800 bg-slate-950 p-4">
                <div className="flex items-center justify-between gap-3">
                  <div>
                    <p className="font-bold text-white">{item.email}</p>
                    <p className="text-xs text-slate-500">{item.projectName || 'Bez projektu'} • {new Date(item.createdAt).toLocaleString('cs-CZ')}</p>
                  </div>
                  <span className={`rounded-full px-3 py-1 text-xs font-black ${item.geoStatus === 'OUT_OF_RADIUS' ? 'bg-amber-950 text-amber-300' : 'bg-rose-950 text-rose-300'}`}>
                    {item.geoStatus}
                  </span>
                </div>
                {item.distanceFromProjectM !== null && item.distanceFromProjectM !== undefined && (
                  <p className="mt-2 text-sm text-slate-300">Odchylka od stavby: {metersLabel(item.distanceFromProjectM)}</p>
                )}
              </div>
            ))}
            {!alerts.length && <p className="text-sm text-slate-500">Aktuálně nejsou žádná GPS upozornění.</p>}
          </div>
        </div>
      </section>
    </div>
  );
}
