export function ReportsPage({ db }) {
  const revenue = (db.invoices || []).reduce((sum, item) => sum + Number(item.amount || 0), 0);
  const areas = (db.components || []).reduce((sum, item) => sum + Number(item.surfaceArea || 0), 0);
  const productionCost = Number(db.company?.costPerSqMeter || 0) * areas;
  const sales = Number(db.company?.sellPerSqMeter || 0) * areas;
  const margin = sales - productionCost;
  const autoInvoices = (db.invoices || []).filter((item) => item.autoGenerated).length;
  const outsideAttendance = (db.attendance || []).filter((item) => item.geoStatus === 'OUT_OF_RADIUS').length;
  const logPhotos = (db.logs || []).reduce((sum, item) => sum + (Array.isArray(item.attachments) ? item.attachments.length : 0), 0);

  const rows = [
    ['Počet projektů', db.projects?.length || 0],
    ['Počet logů', db.logs?.length || 0],
    ['Počet faktur', db.invoices?.length || 0],
    ['Auto faktury', autoInvoices],
    ['Docházka mimo stavbu', outsideAttendance],
    ['Fotky v deníku', logPhotos],
    ['Vyrobená plocha', `${areas.toFixed(2)} m²`],
    ['Fakturace', `€ ${revenue.toFixed(2)}`],
    ['Výrobní náklad', `€ ${productionCost.toFixed(2)}`],
    ['Prodejní hodnota', `€ ${sales.toFixed(2)}`],
    ['Marže', `€ ${margin.toFixed(2)}`]
  ];

  return (
    <div className="rounded-3xl border border-slate-800 bg-slate-900 p-6">
      <h2 className="mb-4 text-lg font-black text-emerald-400">Reporty a ekonomický přehled</h2>
      <div className="divide-y divide-slate-800">
        {rows?.map(([label, value]) => (
          <div key={label} className="flex items-center justify-between py-3">
            <span className="text-sm font-bold text-slate-300">{label}</span>
            <span className="text-sm font-black text-white">{value}</span>
          </div>
        ))}
      </div>
    </div>
  );
}
