import { useMemo, useState } from 'react';
import { MonterInvoicesPanel } from './MonterInvoicesPanel.jsx';

function todayDate() {
  return new Date().toISOString().slice(0, 10);
}

function firstDayOfMonth() {
  const now = new Date();
  return new Date(now.getFullYear(), now.getMonth(), 1).toISOString().slice(0, 10);
}

function formatMoney(value, currency = 'CZK') {
  return new Intl.NumberFormat('cs-CZ', { style: 'currency', currency }).format(Number(value || 0));
}

function formatDate(value) {
  if (!value) return '—';
  return new Date(value).toLocaleDateString('cs-CZ');
}

export function InvoicesPage({ user, db, token, onCreate, onAutoCreate, onPay }) {
  const [manualMessage, setManualMessage] = useState('');
  const [autoMessage, setAutoMessage] = useState('');
  const [autoError, setAutoError] = useState('');
  const [manualError, setManualError] = useState('');
  const [autoForm, setAutoForm] = useState({
    employeeId: user.role === 'MONTER' ? user.id : '',
    projectId: '',
    periodFrom: firstDayOfMonth(),
    periodTo: todayDate(),
    hourlyRate: '280',
    logRate: '150',
    bonusAmount: '0',
    currency: 'CZK',
    note: ''
  });

  const invoices = db.invoices || [];
  const users = db.users || [];
  const projects = db.projects || [];

  const visibleInvoices = useMemo(() => {
    if (user.role !== 'MONTER') return invoices;
    return invoices.filter((invoice) => invoice.employeeId === user.id || invoice.clientName === user.email);
  }, [invoices, user]);

  const autoInvoicesCount = visibleInvoices.filter((invoice) => invoice.autoGenerated).length;
  const unpaidCount = visibleInvoices.filter((invoice) => invoice.status === 'ISSUED').length;
  const totalAmount = visibleInvoices.reduce((sum, invoice) => sum + Number(invoice.amountTotal || invoice.amount || 0), 0);
  const canMarkPaid = ['SUPERADMIN', 'REDITEL', 'ADMINISTRACE'].includes(user.role);

  async function handleManualSubmit(event) {
    event.preventDefault();
    setManualMessage('');
    setManualError('');
    try {
      await onCreate({
        invoiceNumber: event.target.invoiceNumber.value,
        amount: event.target.amount.value,
        clientName: event.target.clientName.value,
        dueDate: event.target.dueDate.value || null,
        projectId: event.target.projectId.value || null,
        note: event.target.note.value,
        currency: event.target.currency.value,
        vatRate: event.target.vatRate.value,
        employeeId: user.role === 'MONTER' ? user.id : (event.target.employeeId?.value || null)
      });
      event.target.reset();
      setManualMessage('Faktura byla vystavena.');
    } catch (error) {
      setManualError(error.message || 'Vystavení faktury selhalo');
    }
  }

  async function handleAutoSubmit(event) {
    event.preventDefault();
    setAutoMessage('');
    setAutoError('');
    try {
      await onAutoCreate({
        employeeId: user.role === 'MONTER' ? user.id : autoForm.employeeId,
        projectId: autoForm.projectId || null,
        periodFrom: `${autoForm.periodFrom}T00:00:00.000Z`,
        periodTo: `${autoForm.periodTo}T23:59:59.999Z`,
        hourlyRate: autoForm.hourlyRate,
        logRate: autoForm.logRate,
        bonusAmount: autoForm.bonusAmount,
        currency: autoForm.currency,
        note: autoForm.note
      });
      setAutoMessage('Automatická faktura podle docházky a práce byla vytvořena.');
    } catch (error) {
      setAutoError(error.message || 'Automatická faktura selhala');
    }
  }

  return (
    <div className="space-y-6">
      {token && (
        <MonterInvoicesPanel token={token} user={user} db={db} />
      )}
      <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
        <StatCard title="Moje / viditelné faktury" value={visibleInvoices.length} tone="text-white" />
        <StatCard title="Automaticky generované" value={autoInvoicesCount} tone="text-emerald-400" />
        <StatCard title="K úhradě" value={unpaidCount} tone="text-amber-400" />
        <StatCard title="Celkový objem" value={formatMoney(totalAmount)} tone="text-blue-400" compact />
      </section>

      <section className="grid gap-6 xl:grid-cols-[minmax(0,0.95fr)_minmax(0,1.05fr)]">
        <div className="space-y-4 rounded-3xl border border-slate-800 bg-slate-900 p-5">
          <div>
            <h2 className="text-lg font-black text-blue-400">Ruční vystavení faktury</h2>
            <p className="mt-1 text-sm text-slate-400">Pro klasické ruční zadání nebo rychlé interní vyúčtování.</p>
          </div>

          <form onSubmit={handleManualSubmit} className="space-y-3">
            <div className="grid gap-3 md:grid-cols-2">
              <InputField name="invoiceNumber" label="Číslo faktury" placeholder="FA-2026-001" required />
              <InputField name="amount" label="Částka bez DPH" type="number" step="0.01" placeholder="12500" required />
            </div>
            <div className="grid gap-3 md:grid-cols-2">
              <InputField name="clientName" label="Klient / zaměstnanec" placeholder={user.role === 'MONTER' ? user.email : 'Název klienta / e-mail zaměstnance'} defaultValue={user.role === 'MONTER' ? user.email : ''} />
              <InputField name="dueDate" label="Splatnost" type="date" />
            </div>
            <div className="grid gap-3 md:grid-cols-2">
              <SelectField name="projectId" label="Projekt">
                <option value="">Všechny / bez projektu</option>
                {projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}
              </SelectField>
              {user.role !== 'MONTER' ? (
                <SelectField name="employeeId" label="Přiřadit zaměstnanci">
                  <option value="">Bez zaměstnance</option>
                  {users.map((member) => <option key={member.id} value={member.id}>{member.email}</option>)}
                </SelectField>
              ) : (
                <InputField name="employeeId_hidden" label="Zaměstnanec" defaultValue={user.email} disabled />
              )}
            </div>
            <div className="grid gap-3 md:grid-cols-2">
              <SelectField name="currency" label="Měna" defaultValue="CZK">
                <option value="CZK">CZK</option>
                <option value="EUR">EUR</option>
              </SelectField>
              <InputField name="vatRate" label="DPH %" type="number" step="0.1" defaultValue="0" />
            </div>
            <TextAreaField name="note" label="Poznámka" placeholder="Co fakturuješ / interní komentář" rows={3} />
            {manualMessage && <MessageBox tone="success">{manualMessage}</MessageBox>}
            {manualError && <MessageBox tone="error">{manualError}</MessageBox>}
            <button className="rounded-2xl bg-emerald-600 px-4 py-3 text-sm font-black uppercase text-white">Vystavit ručně</button>
          </form>
        </div>

        <div className="space-y-4 rounded-3xl border border-slate-800 bg-slate-900 p-5">
          <div>
            <h2 className="text-lg font-black text-emerald-400">Automatická faktura podle práce a docházky</h2>
            <p className="mt-1 text-sm text-slate-400">Spočítá odpracované hodiny z docházky, počet denních záznamů a vytvoří interní fakturu / podklad k vyúčtování.</p>
          </div>

          <form onSubmit={handleAutoSubmit} className="space-y-3">
            {user.role !== 'MONTER' ? (
              <SelectField label="Zaměstnanec" value={autoForm.employeeId} onChange={(event) => setAutoForm((current) => ({ ...current, employeeId: event.target.value }))}>
                <option value="">Vyber zaměstnance</option>
                {users.map((member) => <option key={member.id} value={member.id}>{member.email}</option>)}
              </SelectField>
            ) : (
              <InputField label="Zaměstnanec" defaultValue={user.email} disabled />
            )}

            <SelectField label="Projekt" value={autoForm.projectId} onChange={(event) => setAutoForm((current) => ({ ...current, projectId: event.target.value }))}>
              <option value="">Všechny projekty</option>
              {projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}
            </SelectField>

            <div className="grid gap-3 md:grid-cols-2">
              <InputField label="Od" type="date" value={autoForm.periodFrom} onChange={(event) => setAutoForm((current) => ({ ...current, periodFrom: event.target.value }))} required />
              <InputField label="Do" type="date" value={autoForm.periodTo} onChange={(event) => setAutoForm((current) => ({ ...current, periodTo: event.target.value }))} required />
            </div>

            <div className="grid gap-3 md:grid-cols-3">
              <InputField label="Sazba / hodina" type="number" step="0.01" value={autoForm.hourlyRate} onChange={(event) => setAutoForm((current) => ({ ...current, hourlyRate: event.target.value }))} required />
              <InputField label="Sazba / denní záznam" type="number" step="0.01" value={autoForm.logRate} onChange={(event) => setAutoForm((current) => ({ ...current, logRate: event.target.value }))} />
              <InputField label="Bonus / korekce" type="number" step="0.01" value={autoForm.bonusAmount} onChange={(event) => setAutoForm((current) => ({ ...current, bonusAmount: event.target.value }))} />
            </div>

            <SelectField label="Měna" value={autoForm.currency} onChange={(event) => setAutoForm((current) => ({ ...current, currency: event.target.value }))}>
              <option value="CZK">CZK</option>
              <option value="EUR">EUR</option>
            </SelectField>

            <TextAreaField label="Poznámka do faktury" value={autoForm.note} onChange={(event) => setAutoForm((current) => ({ ...current, note: event.target.value }))} rows={3} placeholder="Např. montáž, servis, pohotovost, přesčasy" />

            <div className="rounded-2xl border border-slate-800 bg-slate-950 p-4 text-sm text-slate-300">
              <p className="font-bold text-white">Jak to funguje</p>
              <ul className="mt-2 space-y-1 text-slate-400">
                <li>• páruje příchod a odchod z docházky</li>
                <li>• počítá odpracované hodiny za zvolené období</li>
                <li>• přičítá počet záznamů ze stavebního deníku</li>
                <li>• vytvoří interní fakturu s detailním souhrnem</li>
              </ul>
            </div>

            {autoMessage && <MessageBox tone="success">{autoMessage}</MessageBox>}
            {autoError && <MessageBox tone="error">{autoError}</MessageBox>}
            <button className="rounded-2xl bg-blue-600 px-4 py-3 text-sm font-black uppercase text-white">Vygenerovat automaticky</button>
          </form>
        </div>
      </section>

      <section className="space-y-3">
        {visibleInvoices.map((invoice) => {
          const summary = invoice.summaryJson || {};
          return (
            <div key={invoice.id} className="rounded-3xl border border-slate-800 bg-slate-900 p-5">
              <div className="flex flex-col gap-4 md:flex-row md:items-start md:justify-between">
                <div className="space-y-2">
                  <div className="flex flex-wrap items-center gap-2">
                    <p className="text-lg font-black text-white">FA: {invoice.invoiceNumber}</p>
                    {invoice.autoGenerated && <span className="rounded-full border border-emerald-700 bg-emerald-950/20 px-3 py-1 text-[11px] font-black uppercase tracking-wider text-emerald-300">AUTO</span>}
                    <span className={`rounded-full border px-3 py-1 text-[11px] font-black uppercase tracking-wider ${invoice.status === 'ZAPLACENO' ? 'border-emerald-700 bg-emerald-950/20 text-emerald-300' : 'border-amber-700 bg-amber-950/20 text-amber-300'}`}>{invoice.status}</span>
                  </div>
                  <p className="text-sm text-slate-300">Příjemce / zaměstnanec: <span className="font-bold text-white">{invoice.clientName || '—'}</span></p>
                  <p className="text-xs text-slate-500">Vytvořeno: {formatDate(invoice.createdAt)} • Splatnost: {formatDate(invoice.dueDate)}</p>
                  {(invoice.periodFrom || invoice.periodTo) && <p className="text-xs text-slate-400">Období: {formatDate(invoice.periodFrom)} – {formatDate(invoice.periodTo)}</p>}
                  {invoice.note && <p className="text-sm text-slate-300">{invoice.note}</p>}
                </div>

                <div className="text-right">
                  <p className="text-xl font-black text-amber-400">{formatMoney(invoice.amountTotal || invoice.amount, invoice.currency || 'CZK')}</p>
                  <p className="mt-1 text-xs text-slate-500">Bez DPH: {formatMoney(invoice.amount, invoice.currency || 'CZK')}</p>
                  {canMarkPaid && invoice.status === 'ISSUED' ? (
                    <button onClick={() => onPay({ id: invoice.id })} className="mt-3 rounded-xl border border-rose-800 bg-rose-950/40 px-4 py-2 text-xs font-black uppercase text-rose-300">Označit jako zaplacené</button>
                  ) : null}
                </div>
              </div>

              {(invoice.autoGenerated || summary.workHours || summary.logEntries) && (
                <div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-5">
                  <MiniMetric label="Hodiny" value={`${invoice.workHours ?? summary.workHours ?? 0} h`} />
                  <MiniMetric label="Docházkové dny" value={invoice.attendanceDays ?? summary.attendanceDays ?? 0} />
                  <MiniMetric label="Denní záznamy" value={invoice.logEntries ?? summary.logEntries ?? 0} />
                  <MiniMetric label="Sazba / hod" value={invoice.unitRate ? formatMoney(invoice.unitRate, invoice.currency || 'CZK') : '—'} />
                  <MiniMetric label="Bonus" value={formatMoney(invoice.bonusAmount || summary.bonusAmount || 0, invoice.currency || 'CZK')} />
                </div>
              )}
            </div>
          );
        })}

        {!visibleInvoices.length && (
          <div className="rounded-3xl border border-slate-800 bg-slate-900 p-6 text-sm text-slate-500">
            Zatím tu nejsou žádné faktury. Zkus ruční vystavení nebo automatické vytvoření z docházky.
          </div>
        )}
      </section>
    </div>
  );
}

function StatCard({ title, value, tone, compact = false }) {
  return (
    <div className="rounded-3xl border border-slate-800 bg-slate-900 p-5">
      <p className="text-xs font-black uppercase tracking-widest text-slate-500">{title}</p>
      <p className={`mt-3 ${compact ? 'text-xl' : 'text-2xl'} font-black ${tone}`}>{value}</p>
    </div>
  );
}

function InputField({ label, name, ...props }) {
  return (
    <label className="block space-y-2">
      {label && <span className="text-xs font-black uppercase tracking-widest text-slate-500">{label}</span>}
      <input name={name} className="w-full rounded-2xl border border-slate-800 bg-slate-950 px-4 py-3 text-sm text-white outline-none disabled:opacity-70" {...props} />
    </label>
  );
}

function SelectField({ label, name, children, ...props }) {
  return (
    <label className="block space-y-2">
      {label && <span className="text-xs font-black uppercase tracking-widest text-slate-500">{label}</span>}
      <select name={name} className="w-full rounded-2xl border border-slate-800 bg-slate-950 px-4 py-3 text-sm text-white outline-none" {...props}>
        {children}
      </select>
    </label>
  );
}

function TextAreaField({ label, name, rows = 3, ...props }) {
  return (
    <label className="block space-y-2">
      {label && <span className="text-xs font-black uppercase tracking-widest text-slate-500">{label}</span>}
      <textarea name={name} rows={rows} className="w-full rounded-2xl border border-slate-800 bg-slate-950 px-4 py-3 text-sm text-white outline-none" {...props} />
    </label>
  );
}

function MessageBox({ tone, children }) {
  const classes = tone === 'success'
    ? 'border-emerald-900 bg-emerald-950/30 text-emerald-300'
    : 'border-rose-900 bg-rose-950/30 text-rose-300';
  return <div className={`rounded-2xl border px-4 py-3 text-sm ${classes}`}>{children}</div>;
}

function MiniMetric({ label, value }) {
  return (
    <div className="rounded-2xl border border-slate-800 bg-slate-950 p-4">
      <p className="text-xs font-black uppercase tracking-widest text-slate-500">{label}</p>
      <p className="mt-2 text-sm font-black text-white">{value}</p>
    </div>
  );
}
